version: "3"

services:
  web:
    build: .

    ports:
      - "8000:8000"
    working_dir: /code/carbon_intelligence
    volumes:
      - "./data:/data"
      - "./src:/code"

    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "./dbdata:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: carbonfreecontainer
