# Generated by Django 3.0.5 on 2020-04-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fuel', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Natural Gas'), ('water', 'Water')], max_length=63)),
                ('unit', models.CharField(choices=[('kWh', 'kWh'), ('m3', 'm3')], max_length=63)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Building')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField()),
                ('reading_date_time', models.DateTimeField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.Meter')),
            ],
        ),
    ]
